### ISSUE TITLE
Annotating vcf with TDB information

### ISSUE THREAD

**Issue by gevro** [ACEnglish/tdb#1]
Hi,
We have proband VCFs that we would like to annotate with a population reference TDB file (HPRC). What is the best way to do this?

Thanks

**Comment by ACEnglish** [comment]
Hello,

There currently isn't a command to accomplish this. However, I can make one fairly easily if let me know which `tdb query` you would like to add. I imagine you're likely looking for `allele_cnts` and `allele_cnts_bylen`? The other standard queries which may be amenable to the task would be `methyl`, `comp_poly_score`, and `len_poly_score`. Each of them would need specific parsers to ingest the query output to create the correct INFO fields.

Have a great day,
~/Adam English

**Comment by gevro** [comment]
Thanks so much! allele_cnts_bylen would be what we want. Because we would want to know for locus in a proband VCF what the distribution of allele lengths is in the reference database.

**Comment by ACEnglish** [comment]
Cool. TRs are a little unusual for VCFs which was the motivation behind tdb. I could build something that would force the information into the VCF that the user would then need to extract for analysis. Something like:

```
##INFO=<ID=TDBAF,Type=Float,Number=R,Description="Allele frequency from TDB">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA24385
chr1    12345    ATCGATCGATCGATCG    ATCGATCGATCGATCGATCG,ATCGATCGATCGATCGATCGATCG    .    .    TDBAF=0.1,0.3,0.2...
```

So there would be three allele frequencies (`Number=R`), one for the reference allele and one for each alt in that order. 

However, it may be more in the spirit of TDB if I were to create a command such as `tdb vcf_to_table` which would search for the `LocusID` and `allele_number` of each VCF entry and write as a tsv. This would allow us to skip the VCF workflow which would be: 1) tdb parses the new VCF, 2) TDB extracts the relevant information, 3) TDB puts the information into the VCF, 4) the user parses the information back out of the VCF. 

A more tdb-like workflow would be:

```bash
tdb query allele_cnts_bylen samples.tdb > allele_cnts.tsv
tdb vcf_to_table your_new_sample.vcf.gz > new_sample.tsv
```

And for analysis:
```python
import pandas as pd
sample = pd.read_csv("new_sample.tsv", sep='\t').set_index( <tbd> )
annotations = pd.read_csv("allele_cnts.tsv").set_index( <tdb> )

data = sample.join(annotations)
#Everything is ready for analysis/plotting
```

I prefer the latter because it immediately make the data ready for analysis and is similar to what we've been building as [notebooks](https://github.com/ACEnglish/tdb/blob/main/notebooks/)

**Comment by gevro** [comment]
That new option you suggest sounds great! So it sounds like we just need a vcf_to_table command?

However, is there a way to build into the vcf_to_table command to also take the tdb database as an input so that vcf_to_table knows to pull out only those loci that are in the tdb database? Because the vcf files will otherwise have many other irrelevant loci. Unless you think the final join step would take care of that.

Even better would be a single command that does all of this. Input tdb + vcf, and it outputs an annotated tsv file.

**Comment by ACEnglish** [comment]
vcf_to_table would need an existing tdb in order to add the correct primary keys (e.g. locus_id / allele_number) that can tie the new vcf to the annotation. The `pd.join` would handle the 'only loci in the tdb' as it would simply add `NaN` to alleles that are unique to the new vcf.

I'll keep an eye out while implementing this for use-optimizations. Right now I don't see a sleek design around a single command, but we'll see. I'll update you... Monday or Tuesday at the latest.

**Comment by gevro** [comment]
Might it be possible to also annotate with mean and std-dev (or other variance measure) of the allele lengths? That way there might be an easy way to filter for those loci in the subject VCF that have an abnormal allele length.

**Comment by ACEnglish** [comment]
I'm certain that information is readily available and would be derivable. As an update on this (since I promised something by today) is that I have written a new command `tdb dump` which will create a giant, flat, de-normalized tsv file of all the information contained in the database. The first idea I had is that one could do something like:

```bash
tdb create -o new_sample.tdb new_sample.vcf.gz
tdb dump new_sample.tdb > data.tsv
tdb query allele_cnts_bylen reference_samples.tdb > allele_cnts.tsv
```

These files could be analyzed by first joining them on their location:
```python
import pandas as pd
data = pd.read_csv("data.tsv", sep='\t')
cnts = pd.read_csv("allele_cnts.tsv", sep='\t')
data.set_index(["chrom", "start", "end", "allele_length"], inplace=True)
cnts.set_index(["chrom", "start", "end", "allele_length"], inplace=True)

# assigning new_sample's alleles an AF
data['knownAF'] = cnts['AF']

# checking mean of variant lengths per-locus
mean_loci_len = data.reset_index().groupby('LocusID')['allele_length'].mean()
std_loci_len = data.reset_index().groupby('LocusID')['allele_length'].std()
mean_std_table = pd.merge(mean_loci_len.to_frame(), std_loci_len.to_frame(), left_index=True, right_index=True)
```

As you can see, `tdb` really is designed to be a database and facilitate users creating queries. A better workflow for the above would be to not export the just-imported VCF from the tdb and directly run `data = tdb.load_tdb('new_sample.tdb')` before running the merge. 

I'm still working to design helpers that would assist users in creating these kinds of merges/joins without expansive knowledge of Pandas. However, I'm going to need more time as this development was interrupted by a time-sensitive project which is currently occupying all my time.

**Comment by gevro** [comment]
No problem! I think with just tdb dump, we can figure out the joins. I suspect other users may appeciate a simpler command that also does the join, but our lab at least can figure out the join.

When will the tdb dump command be released?

**Comment by ACEnglish** [comment]
`tdb dump` is already committed to develop though is minimally tested as this point. Of course if you run into any issues I'll be happy to help/fix them.
